theme: jekyll-theme-minimal
avatar: "lZgWcQEQ_400x400.jpg"
description: Personal Website
title: Home

navbar-links:
  Bio: "#bio"
  Portfolio: "#portfolio"
  What's UX: "#UX"
  Readings: "#Readings"



