remote_theme: daattali/beautiful-jekyll
avatar: "lZgWcQEQ_400x400.jpg"
description: Personal Website
Title: Prado Projects

navbar-links:
  Home: "#top"
  Bio: "#bio"
  Portfolio: "#portfolio"
  What's UX: "#UX"
  Readings: "#Readings"



