remote_theme: daattali/beautiful-jekyll
avatar: "lZgWcQEQ_400x400.jpg"
description: Personal Website
title: ğŸŒ³ğŸ¡ğŸŒ³

navbar-links:
  Bio: "#bio"
  Portfolio: "#portfolio"
  What's UX: "#UX"
  Readings: "#Readings"



